### ISSUE TITLE
JS and CSS files are empty in production mode

### ISSUE THREAD

**Issue by ravionrails** [splitrb/split#146]
In development mode on my local machine it works,
but when i deployed code on production server , 
reset.css / split.css / dashboard.js files are empty

split gem version = 0.5.0

files path in HEAD tag are /split/dashboard.js, /split/reset.css, /split/split.css

**Comment by aruprakshit** [comment]
I am having the same issue @ravionrails

**Comment by tomasdundacek** [comment]
@aruprakshit what version do you use? cannot this be resolved with the latest comment?

**Comment by bfagundez** [comment]
Having the same issue, rails 4.2 , split 1.3 and nginx.

**Comment by bbruneau** [comment]
Likewise, same setup as @bfagundez

**Comment by bfagundez** [comment]
any update on this one?
