### ISSUE TITLE
Remove a user from the experiment

### ISSUE THREAD

**Issue by jchatel** [splitrb/split#157]
Hello,

First of all, thanks for making this great gem.

Now, I have a typical landing page and I'm a/b testing it to measure signed up / conversion rate.

Considering the following scenario:

1 existing user comes to the website, see the landing page and sign in with an existing account. Meaning before signing in, he will see the experiment and therefore increment the counter of participants. But since this person has already sign up,  no new account will be created and no finished function will be called.

As this repeats enough time (mixed with visitors with no account), this could invalidate completely the conclusion drawn on A vs B version. Imaging that 10 existing users see version A and 10 new users see version B, we may conclude wrongly that version A is worse than B.

I did not see anything for addressing this issue. Is there a way I can remove the user from the experiment as soon as he signs in with an existing account by calling a function? Or is there any recommendation for this scenario?

Kind regards,
Jeremy

**Comment by pedrobarros** [comment]
Hi @jchatel, did you ever continued this idea? I have the exact same problem, this would be great for me too :)

**Comment by andrehjr** [comment]
@pjb3 if you're using redis for persistence you can try to remove/change users from a given experiment...  https://github.com/splitrb/split/wiki/Use-Split-outside-a-web-request 

I'm open to ideas on how to improve this part of the gem 🙏
