### ISSUE TITLE
Track conversion values between groups

### ISSUE THREAD

**Issue by mperham** [splitrb/split#158]
We want to a/b test changes and see if they affect our average order value (AOV).  The issue is that split just records a conversion via `finished`.  We'd like to track a number with that conversation and see statistics about how it differs between the A and B groups.  Something like:

`finished('checkout', order.total)`

Ideally tracking median, mode, std dev, etc so the Split UI can tell us if the difference is statistically-relevant.

**Comment by pomartel** [comment]
I also needed the functionality and gave it a shot: https://github.com/pomartel/split/commit/29340ef0cc9776fbf4240e2e577f9e5080d6b96c

You can do `finished('checkout', value: order.total)` and you will get a value and value per participant column in the dashboard for each alternative. It is still a bit rudimentary but it should work and it's backward compatible with the current syntax.
