### ISSUE TITLE
Split working fine locally, but on server only tracking participants, not completions ?

### ISSUE THREAD

**Issue by feliperaul** [splitrb/split#182]
Any idea why it would work fine locally, tracking both participants and completions, but on the server it's not tracking completions ?

If it's tracking participants, I assume everything is fine with Redis, right ?

I'm on 0.6.3

The code for the test is simple:

```
<% ab_test "mandatory_phone_number", "non_mandatory", "mandatory" do |scenario| %>
    <% if scenario == "non_mandatory" %>
      <%= form.text_field :phone, :placeholder => t(:"simple_form.labels.user.phone"), :autocomplete => :off, :rel => "tooltip", :data => {"original-title" => t("new.show.phone_tooltip"), "placement" => "right", "trigger" => "focus"}  %>
    <% else %>
      <%= form.text_field :phone, :placeholder => t(:"simple_form.labels.user.phone"), :autocomplete => :off, :rel => "tooltip", :data => {"original-title" => t("new.show.phone_tooltip"), "placement" => "right", "trigger" => "focus", :validation => 'required'}  %>
    <% end %>
  <% end %>
```

and here's the code for the completion

```
finished('mandatory_phone_number', :reset => false)
```

**Comment by robquesada** [comment]
Same problem here, it works locally but on server is not tracking completions. 

I don't add 'reset: false', I just used 'finished('my_experiment').

I'm starting my a/b testing in a method controller (new) and finishing in another method from the same controller (create). I don't know if start/end in a view/controller it affects.
