### ISSUE TITLE
Expirement version incrementing on every visit

### ISSUE THREAD

**Issue by msaffitz** [splitrb/split#185]
I have an experiment that seems to be resetting with every visit to the page-- the version number increments each time I visit.  I have another experiment where this is not occurring, so I'm reasonably confident this is not something screwy with the setup overall.

The experiment that resets is on the same page as the finished state of the other experiment-- I'm not sure if that's affecting it or not.

Here's the definition of the broken experiment (in haml):

```
- finished('tour_cta')

... (page content) ...

- ab_test({tour_video: :user_registration}, "new", "old") do |version|
  - if version == "old"
    %iframe(height="364" src="http://www.youtube.com/embed/WKt7iT4gNeg" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen)
  - elsif version == "new"
    %iframe(height="364" src="http://www.youtube.com/embed/ntpDgvUFYFg" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen)
```

I'm on 0.6.3 of Split.

**Comment by paneq** [comment]
I am experiencing a similar error. Every call to `ab_test` is resetting the experiment.

**Comment by paneq** [comment]
It's even calling the callback method:

```
config.on_experiment_reset  = -> (example) { Rails.logger.warn("#{example} RESET OCCURED") }
```

**Comment by paneq** [comment]
The reason is `split` is comparing symbolized and non-symbolized keys in Hashes:

```
{"checkbox"=>{"variantId"=>"0"}, "radio"=>{"variantId"=>"1"}}
vs
{:checkbox=>{:variantId=>"0"}, :radio=>{:variantId=>"1"}}
```

Seems to be the problem with metadata:

```
existing_alternatives == @alternatives.map(&:name) && existing_goals == @goals && existing_metadata == @metadata
```

**Comment by tomasdundacek** [comment]
@paneq which version are you on?

**Comment by paneq** [comment]
@tomasdundacek last version.

I fixed this by using strings for metadata in my ruby config:

```ruby
Split.configure do |config|
  config.experiments = {
    agreement: {
      alternatives: ["checkbox", "radio"],
      metadata: {
        "checkbox" => {"variantId" => "0"},
        "radio"    => {"variantId" => "1"},
      }
    }
  }
```

and added an example in https://github.com/splitrb/split/pull/326 for future readme readers.

**Comment by paneq** [comment]
Of course if split called `#stringify_keys` on the `metadata` Hash, that would be a possible fix as well. I guess it is comparing configuration metadata with metadata retrieved from redis.
