### ISSUE TITLE
Metric value?

### ISSUE THREAD

**Issue by glebm** [splitrb/split#201]
Can split use metric with value, such as pageviews or pages / visit?

**Comment by tranngocsam** [comment]
Hi @andrew I have the same question, but couldn't find the answer. Is it feasible? If yes, how?

**Comment by andrew** [comment]
@tranngocsam sorry I'm not sure this would be very easy to do with the current codebase

**Comment by tranngocsam** [comment]
@andrew Thanks for your reply. I added it here https://github.com/tranngocsam/split/commit/6c9be66f733919be3e53327d593115d9f62c3bf4
Would you like to add this feature? And Is it good for merging?

**Comment by andrew** [comment]
@tranngocsam do you fancy opening it as a pull request for review?

**Comment by tranngocsam** [comment]
@andrew Thanks for your interest, I created it here https://github.com/splitrb/split/pull/460
