### ISSUE TITLE
Find assets for Sinatra Dashboard when using Asset_sync gem

### ISSUE THREAD

**Issue by levberlin** [splitrb/split#210]
I found that the dashboard doesn't load Javascript and CSS files in production, but I imagine it's because of the asset_sync gem and not a general problem with the asset pipeline.

Curious if anyone has dealt with this before successfully.

**Comment by iwz** [comment]
There are still some issues related to this. I've outlined another solution which may be useful in https://github.com/splitrb/split/issues/496
