### ISSUE TITLE
Default options for test environment

### ISSUE THREAD

**Issue by gemmaros** [splitrb/split#220]
I know this is a silly question, but I can't for the life of me figure it out.  I just integrated your gem into our app (awesome job, btw) and of course, now a bunch of tests are failing sporadically because the option expected may or may not be the one rendered.  Is there a way to specify only control options for the test environment?  Thanks!

G

**Comment by YoranBrondsema** [comment]
As grinnick.com seems to be down, here is a link to a version on the Wayback Machine: https://web.archive.org/web/20131030043222/http://grinnick.com/posts/a-b-testing-with-split-in-ruby-on-rails
