### ISSUE TITLE
starting ab test in non authenticated environment and trying to finish it in my admin module doesn't work

### ISSUE THREAD

**Issue by t3en4** [splitrb/split#229]
I have the following scenario:

An unauthenticated view where I set my ab_test like this:

ab_test('ab_my_test', 'option_a', ' option_b')

which works perfect.

Now, I need to set the test as finished on my admin module (I need to be logged in as admin), whoever the:

finished('ab_my_test')

doesn't work at all. If I put it on any other unauthenticated method in other controller it works fine.

Is there a way to solve this?

Thanks!

**Comment by andrew** [comment]
Closing as this issue is over 2 years old, please reopen if it's still affecting you.
