### ISSUE TITLE
Disable test?

### ISSUE THREAD

**Issue by brandonparsons** [splitrb/split#244]
From reading through the docs, it seems pretty simple to force a particular variation via query params.  Is there a way to totally disable the test (i.e. use the control option and don't register a hit)?

I'm hitting my site with a script, and the easiest thing to do would be to tack a query param on the end of my URL's to hopefully not throw off the stats (as opposed to trying to filter the IP's of the hosts the scripts are running on).

**Comment by andrew** [comment]
Closing as this issue is over 2 years old, please reopen if it's still affecting you.
