### ISSUE TITLE
Tests with blocks in sinatra views

### ISSUE THREAD

**Issue by alpemaca** [splitrb/split#252]
Currently i can't do a test in a sinatra view

- ab_test("name","option","otherOption") do |text|
%h2= text

Maybe at lib/split/helper.rb, line 42, the condition should be exclude sinatra apps?
41 if block_given?
42    if defined?(capture) # a block in a rails view

When I change manually for this works ok
41 if block_given?
42    yield(ret)

Sorry for my bad english,
Thanks!!

**Comment by andrew** [comment]
Closing as this issue is over 2 years old, please reopen if it's still affecting you.
