### ISSUE TITLE
different views showing different partials within the same 'shared' experiment?

### ISSUE THREAD

**Issue by grimmwerks** [splitrb/split#259]
I've got my app split into using a bunch of different partials; is there a way I can have these partials display different html for the SAME experiment?

Meaning i've got a navigation partial that is going to drop a page while the home page displays the contents of this dropped page in it's view at the same time; I had hoped that if I had the same named experiment but with different options these views would change in sync but it doesn't seem to be the case?

http://stackoverflow.com/questions/24251236/rails-a-b-testing-with-split-multiple-views-sharing-same-experiment-helper-met

**Comment by andrew** [comment]
Closing as this issue is over 2 years old, please reopen if it's still affecting you.
