### ISSUE TITLE
Weights/Percentages Not Sticking

### ISSUE THREAD

**Issue by danielschwartz** [splitrb/split#267]
When set in the configuration file like so:

``` ruby
"20140923_product_reviews" => { :alternatives => [{'hide' => 0.75}, {'show' => 0.25}] }
```

The experiment will still be weighted 1:1. On initialization of alternative the correct weight is being set, but somehow after the fact it is being reset to a weight a 1. I confirmed this by doing the following:

Added a `binding.pry` to the bottom of the initialization method of the `Alternative` class and saw that `@weight` was correctly set. However, after initialization, when looking up the experiment like so: `Split::ExperimentCatalog.find("20140923_product_reviews")` the weights are set back to 1 for both alternatives. 

We're on Split 0.7.2

**Comment by Coedcoe** [comment]
@andrew @danielschwartz I seem to be having similar issues where the weights aren't sticking, they keep defaulting back to 1:1 . Was this issue ever resolved?

**Comment by andrew** [comment]
Closing as this issue it's nearly 2 years old, please reopen if it's still affecting you.

**Comment by neyp** [comment]
This is still happening on the latest version. I ended up creating https://github.com/splitrb/split/issues/521.
