### ISSUE TITLE
Are multiple, progressive goals available?

### ISSUE THREAD

**Issue by yjukaku** [splitrb/split#275]
I was looking at #109 and it seems like it's been merged into master.  From that pull request:

`An experiment can have more than one goals. For example, we might want to see how an alternative might affect sign up conversion, as well as purchase conversion. It's possible that an alternative might increase sign-up conversion, but negatively impact purchase conversion.`

So that makes it seem like multiple, progressive goals are available. But then if you look at the README, it mentions:

```
NOTE: This does not mean that a single experiment can have/complete progressive goals.

Good Example: Test if listing Plan A first result in more conversions to Plan A (goal: "plana_conversion") or Plan B (goal: "planb_conversion").

Bad Example: Test if button color increases conversion rate through multiple steps of a funnel. THIS WILL NOT WORK. 
```

In fact, I am the one who wrote that section in the README. :laughing:   So what is going on here??

**Comment by andrew** [comment]
Is this something you'd be interested improving on the project? Perhaps adding a spec for the expected behaviour would be a good way to get start.

**Comment by benross** [comment]
From a user perspective, this would really distinguish split from other ab tests out there. We are almost always interested in a conversion funnel and need at least 2 data points (eg sign ups and upgrades) as multiple goals.

In the meantime I've been trying to come up with a workaround for this. I was thinking we could track the goals either directly to our database or using a third party analytics service (eg tracking an event in google analytics). But to do this I need to access whether the user is in a test, and can't find any documentation on this. Something like a ab_test_value('my_experiment') that returns the current experiment alternative, or nil if the user is not in an experiment. Does this exist in some form?

**Comment by losvedir** [comment]
@benross - the work around we've been doing is basically setting up multiple experiments, doing `ab_test` to put someone in one of them, and then, based on the outcome of that, bucketing them in the other experiments with probability 1 or 0. Something like:

``` ruby
bucket = ab_test('xp1', 'a', 'b')
if bucket == 'a'
  ab_test('xp2', {'a' => 1}, {'b' => 0})
else
  ab_test('xp2', {'a' => 0}, {'b' => 1})
end
```

Someone is then enrolled in both `xp1` and `xp2` simultaneously, and in either the `a` or `b` versions consistently. It's not ideal, but it works.

One thing to watch out for is that the order of hashes is important, and as given above for `xp2` the `a` experiment is "control". You'll need to make sure that all calls to `ab_test` for `xp2` have the same control as the parameter after the experiment name.

**Comment by benross** [comment]
@losvedir - Brilliant! I had an inkling of doing something like this but was going down a more complicated rabbit hole. Great work around.

And officially offering a beer to anyone who adds this feature to Split :-)

**Comment by henrik** [comment]
Tried clarifying this limitation in #383.

**Comment by benross** [comment]
@andrew and @henrik is there a way this can live somewhere as a feature request? In my team's experience this is still the most frustrating part of using the gem :/

**Comment by andrew** [comment]
Reopened it for you and added some labels

**Comment by andrew** [comment]
https://github.com/splitrb/split/pull/493 has been merged with functionality close to this, so I'm going to close this issue.
