### ISSUE TITLE
Experiments with / in it cannot be deleted or reset via dashboard

### ISSUE THREAD

**Issue by ncri** [splitrb/split#277]
Just tried to delete/reset an experiment with "/" in it. It gives an error because the name is not url escaped and thus changes the delete/reset url.

**Comment by andrew** [comment]
@bartj3 any news on a fix for this issue?

**Comment by bartj3** [comment]
i completely forgot about it :( started on the fix this morning, i've got a failing test but need to dive into it a bit further to actually get it green again.

I was thinking about adding a slug accessor on the Experiment which is an CGI::escaped name, but I didn't get it working yet.

**Comment by craigmcnamara** [comment]
Merry Christmas https://github.com/splitrb/split/pull/349

**Comment by andrew** [comment]
Fixed in #349

**Comment by ncri** [comment]
Thanks!
