### ISSUE TITLE
Rename `finished` to something less generic (`ab_finished`?)

### ISSUE THREAD

**Issue by henrik** [splitrb/split#298]
I don't love the idea of having a method with the generic name `finished` in all my controllers – how about a rename to `ab_finished`?

It would mean less risk of collisions, be consistent with `ab_test`, be more self-documenting and more obvious where it comes from.

**Comment by Bodacious** [comment]
+1

**Comment by Lucasosf** [comment]
:+1:

**Comment by Aerlinger** [comment]
+1 I've been having issues with `finished` colliding with methods I've declared as well.

**Comment by andrew** [comment]
Just merged #389, `ab_finished` will be available in the next release and `finished` will be removed in `2.0.0`
