### ISSUE TITLE
Experiments no longer finishing after upgrading to Rails 4.2.0 and Ruby 2.2.1

### ISSUE THREAD

**Issue by TaylorKolasinski** [splitrb/split#300]
After upgrading our app to rails 4.2.0 from 4.1.7, and ruby from 2.1.5 to 2.2.1, none of the experiments will finish.

**Comment by cdussud** [comment]
It works after downgrading back to Rails 4.1.8 on Ruby 2.2.1. Looks like split isn't compatible with Rails 4.2.0.

**Comment by tomasdundacek** [comment]
Hi @TaylorKolasinski, @cdussud,

I did experience some issues on 4.2.0 as well. Did you try to upgrade to Rails 4.2.1?
Don't you have a method name conflict with the `finished` method?

**Comment by dre-hh** [comment]
can confirm on 4.2.1

**Comment by andrew** [comment]
@dre-hh which version of split are you using?

**Comment by dre-hh** [comment]
1.2.1

**Comment by dre-hh** [comment]
spplit/helper.rb:67  `experiments.any?` returns false

**Comment by dre-hh** [comment]
I've found the error, the experiment name is somehow wrong, i'll try to provide a pull request

**Comment by dre-hh** [comment]
lol, can it be, that u guys have also used the demo code from railscasts to play around with split. It was just using different key names for the ab_test and finished command. XD. Everything is working fine for me now.

**Comment by andrew** [comment]
Closing as this issue it's over a year old, please reopen if it's still affecting you.

**Comment by anicholson** [comment]
We're seeing this in our application, upgrading from Rails 3.2.x to 4.2.latest :/
