### ISSUE TITLE
More participants than visitors

### ISSUE THREAD

**Issue by Bodacious** [splitrb/split#302]
I installed Split on our server two days ago.

Since then, the number of participants in our first experiment has about 10x the number of visitors to the site reported by Google Analytics.

Can you think of any reason why this might be the case? Crawlers?

NOTE - I haven't configured a split with multiple treatments, only the control for now (wanted to find out what our basic conversion rate was first of all)

**Comment by tomasdundacek** [comment]
Hi @Bodacious !

Thanks for the report. I've hit similar issue but haven't figure out on how to "fix" this yet. Very likely, you are getting some crawler requests, that don't have javascript enabled and therefore aren't recorded through Analytics. When I had this issue, sadly the User-Agent of the crawler was a standard User-Agent, not distinguishable from other "normal" requests.

Were you able to find out something more in the meantime before I answered here?

**Comment by andrew** [comment]
Closing as this issue it's over a year old, please reopen if it's still affecting you.

**Comment by Lastimoso** [comment]
I have the same issue. Have someone managed to solve it?
