### ISSUE TITLE
Split has moved to an org, looking for maintainers

### ISSUE THREAD

**Issue by andrew** [splitrb/split#307]
Just an FYI really, I've moved split and some of it's extensions over to a new organisation on GitHub: https://github.com/splitrb

This is mostly to try to increase the bus-factor of the project as I've not used Split myself in well over a year and I don't have much free time to continue to maintain the project. If you would like to be added to the org to help maintain the project going forward please do mention it below.

There are also a number of open issues that need some attention if anyone fancies triaging those: https://github.com/splitrb/split/issues

**Comment by tomasdundacek** [comment]
Hi @andrew!

Me and @mmagnusek would be interested in maintaining the split gem, since we have started using it a lot within our organization (@blueberryapps).

Would you be open to discuss our participation in the project?

Thanks in advance!
Tomáš

**Comment by andrew** [comment]
Hey @tomasdundacek @mmagnusek that sounds great, what kind of things are you looking to change/improve/fix on split?

**Comment by tomasdundacek** [comment]
Well, there are couple of things, we want to improve, examples:

- enabling/disabling of experiments on specific URLs (= when the `ab_test` method would be called on disallowed URL, it would return `control` variant just as if it would be disabled)
- chasing errors similar to #302 (we've also run into this issue)
- #298 for sure
- fix support for `ab_test` method in controllers

From a more general point of view, we want to increase confidence in Split when used with other tools such as Google analytics or Kiss Metrics (try to find out why numbers differ).

Further, we would like to think about supporting multi-site one-repository experiments having `allow_multiple_experiments` still set to `false`. But this last point is an early stage idea.

BR, Tomáš

**Comment by andrew** [comment]
That all sounds great, I'll add you to the org, please do send all improvements as pull requests so they can be reviewed before they are committed to master.

**Comment by tomasdundacek** [comment]
Hi @andrew , 

I think you have seen, that I couldn't manage to find enough time to work on the split repo, therefore I think it would be better for you to try to find someone, who would have more time to work on it. 

Therefore, I apologize, I wanted to ask you to remove me from the collaborators list.

Hopefully, we'll meet at some later time, maybe in another project.

Thanks a lot,
Tomáš

**Comment by andrew** [comment]
Sure, no worries, I've removed you now.
