### ISSUE TITLE
Argument usage error at Experiment#write_to_alternatives ?

### ISSUE THREAD

**Issue by bob-rove** [splitrb/split#311]
[Experiment#write_to_alternatives](https://github.com/splitrb/split/blob/master/lib/split/experiment.rb#L317) accepts argument `alternative_probabilities` but uses instance variable `@alternative_probabilities` instead:

```ruby
def write_to_alternatives(alternative_probabilities, goal = nil)
  alternatives.each do |alternative|
    alternative.set_p_winner(@alternative_probabilities[alternative], goal)
  end
end
```

Technically it's an error, but seems like it just an unnecessary argument :)

**Comment by andrew** [comment]
@bob-rove yeah good spot, would you be up for sending a pull request to remove the excess argument?
