### ISSUE TITLE
Force use control in an ab_test

### ISSUE THREAD

**Issue by tom-alcorn** [splitrb/split#315]
I would like to be able to force the ab_test to serve up the control alternative with a param like force_control=true, which would default to false.

This would help in situations where I only want to run the A/B test on certain types of users (in my case, differentiated by url params), without me having to mess around with the underlying experiment instance to get the control (I define all my experiments in experiments.yml, so I don't have access to the control alternative in the view where I'm calling ab_test).

The end result would look like this

```ruby
ab_test "my_totally_sweet_test" force_control=test_inactive_for_user do
  some_content
end
```

**Comment by tom-alcorn** [comment]
Looks like I could achieve this with a small change to Experiment.next_alternative

**Comment by tom-alcorn** [comment]
Actually adding a check for force_control in Helper.exclude_user? will be the best way

**Comment by andrew** [comment]
Check out this section on overriding alternatives in the readme: https://github.com/splitrb/split#overriding-alternatives

**Comment by tom-alcorn** [comment]
I know there is an option to force with an url parameter but I don't get to control what url params a user lands with, so in the context of my site that will require looking at a user's url params, doing some logic and then redirecting them with a new url param to force the A/B test. I'd like to eliminate the redirect.

**Comment by tom-alcorn** [comment]
This should work now, right? https://github.com/splitrb/split/compare/master...tom-alcorn:force_control

**Comment by andrew** [comment]
I'm off to bed now, I'll check it out in the morning.

**Comment by tomasdundacek** [comment]
Hi @tom-alcorn!

Actually, this diff would make the library Ruby2.0+ only. What is your usecase for forcing the control variant like this?

**Comment by tom-alcorn** [comment]
I have two types of users, search and email, who are differentiated by a url param like type=[search, email]. Sometimes I want to test a variant of my site on one type of user but not the other. 

Right now I'm achieving this with a bit of logic around ab_test defined within one of my helper classes:
```ruby
def do_ab_test(test_name, &content)
  experiment = Split::ExperimentCatalog.find_or_initialize(test_name)
  active = test_active?(experiment)
  if !active
    control = experiment.control
    control_meta = experiment.metadata[control.name]
  end
  if block_given?
    if active
      ab_test(test_name) do |alt, meta|
        yield(alt, meta)
      end
    else
        yield(control, control_meta)
    end
  else
    if active
      ab_test(test_name)
    else
      control
    end
  end
end
```
but this involves initializing the experiment myself, which is not very nice and might break other logic within split.

**Comment by tomasdundacek** [comment]
Actually I think this is part of logic, that should not be included in split itself, because for me it breaks the possibility to get good results out of the test.

Anyways, in this case I would recommend using the `ignore_filter` config option to exclude the users that you want to.

From the docs: https://github.com/splitrb/split#filtering

**Comment by tom-alcorn** [comment]
ignore_filter is almost what I'm looking for, but I'm running multiple tests at once and want to be able to deactivate tests for a given user on a test-by-test basis.

What do you mean when you say it would break the possibility to get good results out of the test?

**Comment by tomasdundacek** [comment]
By breaking the possibility to get good results I meant, that the user would this way be included in the test measurement as having the control variant. In this specific usecase I would recommend using a conditional like 

```ruby
if enabled_for_user?(current_user) && (ab_test('test_name') == 'alternative')
...
else # control variant and users having the test disabled
...
end
```

Similar way I currently separate users in my client project.

**Comment by andrew** [comment]
Closing as this issue it's over a year old, please reopen if it's still affecting you.
