### ISSUE TITLE
symbols by defaults ?

### ISSUE THREAD

**Issue by grosser** [splitrb/split#318]
I feels really weird to me to use strings as names for experiments,
thankfully symbols are also supported, but how about making them the default in the docs ?

Would you merge a PR that changes the Readme to symbols ?
@andrew

**Comment by andrew** [comment]
@grosser it's been awhile since strings were recommended as the default, in the back of the mind I seem to remember some subtle bug as all names will be stored as strings in redis, as long as any symbols that are used are converted to and from strings correctly then I don't see why not.
