### ISSUE TITLE
recording a conversion on a button click

### ISSUE THREAD

**Issue by campgurus** [splitrb/split#325]
Attempting to record sign-ups to an external email list managed with MailChimp such that anyone submitting the for counts as a conversion.

The embedded form does not redirect anywhere, such that I could add the conversion tracking to the controller.  Can I use an on-click event to count conversions.

What is the best way to do this?

**Comment by tomasdundacek** [comment]
Hi @campgurus!

Basically, the best way is to send a AJAX event to your backend on click. There is currently no integrated support for starting/finishing events through JavaScript.

**Comment by campgurus** [comment]
This is helpful, I am doing some research on AJAX.  do i still need a route/controller action or view where i can put e.g. finished(:signup_page_redesign).  my apologies in advance if that is a silly question.

**Comment by tomasdundacek** [comment]
Yes, basically you can setup your own endpoint in your application, call it through AJAX and there call `finished(...)`

**Comment by alexvbush** [comment]
@tomasdundacek I'm working on a similar thing, in my case I use convertkit form. Will split/rails properly and accurately identify that user who just signed up so that it tracks is as success in the right ab test bucket? I'm not that versed in how rails handles sessions/cookies and ajax requests.

**Comment by andrew** [comment]
This issue is over a year old, I'm going to close it now but feel free to comment and request it be reopened if you still need it.
