### ISSUE TITLE
store_override not working?

### ISSUE THREAD

**Issue by mdesanti** [splitrb/split#327]
I have an page that has an A/B test. The alternative to be shown depends on where the user comes from. The idea is that I will be sending some emails that match with alternative A and some that match with alternative B. If the user clicks on the email and visits my page, then he should see the alternative that matches what he saw in the email.

Even though I added this line `config.store_override = true` to my split initializer, overriden values are not being stored.
In case it is useful, here is my initializer:

```
Split.configure do |config|
  config.db_failover = Rails.env.production? # handle redis errors gracefully
  config.db_failover_on_db_error = proc{|error| Rails.logger.error(error.message) }
  config.allow_multiple_experiments = true
  config.enabled = !Rails.env.test?
  config.persistence = Split::Persistence::SessionAdapter
  #config.start_manually = false ## new test will have to be started manually from the admin panel. default false
  config.store_override = true
  config.include_rails_helper = true
end
```

Am I missing something?
Thank you in advanced.

**Comment by andrew** [comment]
Closing as this issue it's over a year old, please reopen if it's still affecting you.
