### ISSUE TITLE
Setting the Redis namespace

### ISSUE THREAD

**Issue by andyw8** [splitrb/split#336]
It seems the README describes two different approaches to setting the Redis namespace:
- `Split::Persistence::RedisAdapter.with_config(...)`
- `Split.redis.namespace = ...`

Only the second approach seems to work.

**Comment by craigmcnamara** [comment]
`Split::Persistence::RedisAdapter.with_config(...)` is to provide a custom context or session_id. `Split.redis.namespace = ...` is the only way to set the main Redis namespace.

**Comment by karmakaze** [comment]
The following worked for me with 1.4.4 (didn't try other versions):
```ruby
Split.configure do |config|
  config.persistence = Split::Persistence::RedisAdapter.with_config(namespace: "user")`
end
```

**Comment by andrew** [comment]
Closing as this issue it's over a year old, please reopen if it's still affecting you.
