### ISSUE TITLE
How can I use this gem with grape api gem?

### ISSUE THREAD

**Issue by hey-jude** [splitrb/split#338]
https://github.com/ruby-grape/grape

I want to do a/b test on my api service, this is built with grape gem.
How can I use split?

**Comment by craigmcnamara** [comment]
`include Split::Helper` should be all you need.

**Comment by kln** [comment]
@hey-jude Did you solve it?
My a/b test starts with user unlogged. How can I keep the user in the same alternative every time?

**Comment by andrew** [comment]
Closing as this issue it's over a year old, please reopen if it's still affecting you.
