### ISSUE TITLE
Custom Algorithm not working for an experiment.

### ISSUE THREAD

**Issue by zzunaid** [splitrb/split#344]
I have created this AbTestService for algorithm to choose alternatives. The following code doesn't work. But when I specify config.algorithm = AbTestService , for all experiments it works . Please let me what is the issue with the following code
   *  Split.configure do |config|
  config.experiments = {
    my_first_experiment: {
    	algorithm: 'AbTestService',
      alternatives: ["1", "2", '3']
    },
  }
end

**Comment by 007sumit** [comment]
Experiment level algorithm configuration is mentioned in the documentation (https://github.com/splitrb/split#experiment-configuration) , but is not supported at code level.

I also faced same situation, and modified the same. Will put PR for it soon.

**Comment by 007sumit** [comment]
FIXED. You can close this issue now.
