### ISSUE TITLE
db_failover FAILED!

### ISSUE THREAD

**Issue by noctivityinc** [splitrb/split#345]
I just started getting alerts from Airbrake.io that my site was down.  Upon inspection I found this error was causing it:

Redis::CommandError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

But when I checked my `initializers/split_config.rb` I found that I have db_failover set to TRUE, so shouldn't have Split handled this gracefully?

```
Split::Dashboard.use Rack::Auth::Basic do |username, password|
  username == APP_CONFIG[:split_username] && password == APP_CONFIG[:split_password]
end

Split.configure do |config|
  config.db_failover = true # handle redis errors gracefully
  config.db_failover_on_db_error = proc{|error| Rails.logger.error(error.message) }
  config.allow_multiple_experiments = true
  config.enabled = true
  config.store_override = true
end
```

**Comment by dwbutler** [comment]
Looks like only a few very specific exceptions are rescued:

https://github.com/splitrb/split/blob/ffe35d66210661382ab5da75603d55875f3ade2a/lib/split/helper.rb#L19

**Comment by dwbutler** [comment]
Though when I checked, `Redis::CommandError` does inherit from `Redis::BaseError`...

**Comment by andrew** [comment]
Closing as this issue it's over a year old, please reopen if it's still affecting you.
