### ISSUE TITLE
Changing multiple elements in one test

### ISSUE THREAD

**Issue by davepmarshall** [splitrb/split#353]
I'm researching A/B testing solutions at the moment. I've enjoyed reading the documentation and examples but want to check I'm not missing something.

After setting up an experiment, e.g.

```
<h2><%= ab_test('form_title', 'Sign up now', 'Join Today') %></h2>
```

Is it possible to refer to this same experiment in another location to change another element of the design, in sync with what the user has been allocated? Is it possible on the same page? Is it possible across multiple pages?

**Comment by andrew** [comment]
@davepmarshall yep, once a user has been given an alternative for the `form_title` experiement they will always get the same, so you could do something like this elsewhere in your app:

<a href="#"><%= ab_test('form_title', 'Sign up now', 'Join Today') ==  'Sign up now' ? 'Sign up' : 'Join' %></a>

So basically checking the return from the same method, with the same arguments and you'll get the same value every time for a given visitor.

**Comment by andrew** [comment]
Closing as this issue it's over a year old, please reopen if it's still affecting you.
