### ISSUE TITLE
Sinatra dependency and Rails 5

### ISSUE THREAD

**Issue by jlecour** [splitrb/split#354]
Hi,

Currently Split can't be used in a Rails 5 app because of the Rack dependency of Sinatra.

Rails 5 requires `rack (= 2.0.0.alpha)` and Sinatra requires `rack (~> 1.1)`.

I've not spent enough time inside split to have an educated guess of the complexity to either remove te dependency or to allow a wider dependency of Rack and/or Sinatra.

Anyway, thanks a lot for making and maintaining Split. It's been very helpful.

**Comment by existent-co-uk** [comment]
This is going to cause me a problem too, when I come to move our project to Rails 5. It looks like some work is happening in the Sinatra codebase to support rack 2.x

**Comment by jlecour** [comment]
Sinatra `1.4.x` supports only Rack `~> 1.5`, but Sinatra `2.0.0-alpha` supports Rack `= 2.0.0.alpha`.

**Comment by andrew** [comment]
I'm hopeful that there will be a new version of sinatra soon that solves this issue, the [gemspec on master](https://github.com/sinatra/sinatra/blob/master/sinatra.gemspec#L18) current requires rack 2.0.0.alpha:

    s.add_dependency 'rack', '= 2.0.0.alpha'

In the short term you might be able to get it bundling by adding the following to your rails 5 gemfile:

    gem 'sinatra', github: 'sinatra/sinatra'

**Comment by jlecour** [comment]
@andrew It works for me. Thanks.
