### ISSUE TITLE
ERROR: simple_random on dashboard

### ISSUE THREAD

**Issue by khrtz** [splitrb/split#355]
Really been resolved? https://github.com/splitrb/split/issues/272

I just heppen now from simple_random at base method. Incidentally,split version is latest.
Although the cause is not known clearly. Because it has been delete Cookie in the middle of a AB test  with DevTools maybe?

**Comment by divineforest** [comment]
@khrtz the fix is in the master, pls try it

**Comment by andrew** [comment]
Fixed by #408
