### ISSUE TITLE
get current experiment

### ISSUE THREAD

**Issue by deha23** [splitrb/split#370]
How can I get the current experiment name after the experiment has been started?

**Comment by ChanChar** [comment]
@deha23 Could you clarify where you wanted to see the name (eg. view vs controller). You can setup metadata which will allow you to use methods to figure out the name of an ongoing experiment. Instructions for these can be found on [split's readme](https://github.com/splitrb/split#experiment-configuration).

**Comment by andrew** [comment]
Closing as this issue it's nearly a year old, please reopen if it's still affecting you.
