### ISSUE TITLE
Safer URL override naming scheme

### ISSUE THREAD

**Issue by henrik** [splitrb/split#381]
README says

> If you have an experiment called button_color with alternatives called red and blue used on your homepage, a url such as:
>
> http://myawesomesite.com?button_color=red

This seems a bit dangerous to me – running a test named foo and also using a foo=true param for something else, that would affect the A/B test.

Might it be a good idea to change the naming scheme to something more explicit, like `ab_button_color` or `split_button_color` or similar?

**Comment by andrew** [comment]
I believe that if you override an alternative using a url parameter that it won't be tracked towards the goal statistics but you are right that it could lead to confusion, we'll need to handle deprecating the existing behaviour if we change it in a future version. Fancy sending a pull request to kick it off?

**Comment by henrik** [comment]
Happy to provide a PR. About deprecation, maybe we could just change it, note it as backwards-incompatible and bump the major version (if this gem follows semver)?

**Comment by andrew** [comment]
Yeah we can bump to 2.0 to cover the breaking change

**Comment by ccallebs** [comment]
@andrew @henrik The proposed solution doesn't really fix the problem, just makes it less likely to occur.  Would something like this be overkill?

```
http://www.domain.com/my/url?ab_test=button_color/red
# or
http://www.domain.com/my/url?ab_test=button_color@red
```

Then you would just have to provide documentation that "ab_test" was a protected keyword. It could even be configurable to something else.

**Comment by henrik** [comment]
@ccallebs Hm, interesting idea!

To me the prefix strikes a good balance between convenience and making mistakes very unlikely. But toying with your idea, perhaps a bracket syntax like Rails forms could make sense: ab_test[button_color]=red

Again, though, I'm more inclined to just the prefix, personally.

**Comment by andrew** [comment]
I like the idea of `?ab_test[button_color]=red`, perhaps with the option of configuring the name of the parameter (ab_test) in case of clashes with a particular application.

**Comment by henrik** [comment]
Made a PR. Not sure I understand the configurable parameter name – what kind of situation do you see where some application would use an "ab_test" param for another purpose? Seems unlikely enough that we could probably wait until someone reports such an error.
