### ISSUE TITLE
Change "ab_" prefix to "split_"?

### ISSUE THREAD

**Issue by henrik** [splitrb/split#396]
Would a "split_" prefix be better than "ab_" for methods like "ab_test" (so "split_test" etc), since there can be more than two options? Since we might release a 2.0 with other breaking changes, this might be a good time to also make this change, if it makes sense.

[Wikipedia gives the impression](https://en.wikipedia.org/wiki/A/B_testing) that the term "A/B testing" only covers two alternatives.

I don't feel strongly about this – I think "ab_" is quite acceptable even if it might technically be a bit incorrect – but I thought I'd bring it up while 2.0 is in the works.

cc @joakimk

**Comment by andrew** [comment]
I don't have any strong feelings either way, `split_` might be more likely to clash with other methods the user defined like `split_name` for example but it's an edge case either way.
