### ISSUE TITLE
Version of tests automatically resets...

### ISSUE THREAD

**Issue by coworkingon-es** [splitrb/split#401]
Hi there,
I have an issue with A/B testing. I don't know why, but the version automatically resets every X minutes. I haven't changed anything, and the version shows more than 400... Any clue of why this is happening? 
I have another test running without problem. This test has I18N inside:
    <%= f.submit ab_test('text_button', t('.submit'), t('.submit2'), t('.submit3'), t('.submit4')), class: 'button expand action  cmn-t-shake', style:'background-color:#FDB714!important' %> 
Thanks!
![seleccion_458](https://cloud.githubusercontent.com/assets/6212799/15565800/5a2a74d4-231d-11e6-85b8-77a0fea4a4b3.png)

**Comment by coworkingon-es** [comment]
Any clue...?

**Comment by andrew** [comment]
Can you provide more details about your configuration?

**Comment by coworkingon-es** [comment]
Hi Andrew,
Many thanks for your answer. I am using Ruby on Rails with ruby 2.1.6p336 (2015-04-13 revision 50298)  
Rails 4.1.0
URL is www.spaces-on.com

I don't know if you need any more details?

Thanks!

**Comment by andrew** [comment]
@coworkingon-es have you made any changes to the split configuration or cookie setup in your app?

**Comment by coworkingon-es** [comment]
Hi Andrew,
No, I have another test running and it works perfectly well, that's why I don't really understand what's happening...
Thanks!

**Comment by andrew** [comment]
it's very odd, i wonder if it has something to do with the translation methods returning something different every time? Perhaps adding `.to_s` to the end of `t('.submit')`, `t('.submit2')` etc will help?

**Comment by coworkingon-es** [comment]
Hi andrew, thanks, I am going to try and tell you. Yes, i think it is because of translation.

**Comment by coworkingon-es** [comment]
Hi Andrew, 
This is driving me crazy... :( It still resets... I understand something is wron with I18N but can't find what... Now it has version more than 11.000!
![seleccion_548](https://cloud.githubusercontent.com/assets/6212799/15870960/92667fe4-2cf2-11e6-9710-71ca04db6140.png)

**Comment by andrew** [comment]
Couple other things to try:

- Change the test name to a symbol: 
    ab_test(:text_button, t('.submit'), t('.submit2'), t('.submit3'), t('.submit4'))

- Try configuring the test in an initializer instead: https://github.com/splitrb/split#experiment-configuration

```ruby
Split.configure do |config|
  config.experiments = {
    text_button: {
      alternatives: [t('.submit'), t('.submit2'), t('.submit3'), t('.submit4')]
    }
  }
end
```

**Comment by andrew** [comment]
This issue is over a year old, I'm going to close it now but feel free to comment and request it be reopened if you still need it.
