### ISSUE TITLE
Complete test only once or get distinct completitions

### ISSUE THREAD

**Issue by herenow** [splitrb/split#402]
Hi,

Here's my scenario: I have an event called `contact request`, this event may be triggered 100 times by a single user, or just once. It is not common for a single user to trigger this event 100 times, but it happens occasionally, if this happens, it would screw up the test.

Is there a way to tell `split` to record when the event is completed only once per participant/session?

From what I observed, using `ab_finished(:test, reset: false)` will not reset the participant, but he may still increment the `completed` column in the experiment if I call `ab_finished` again.

Which may cause the `non finished` to go negative:

![](https://dl.dropboxusercontent.com/spa/olbum5amkbk9whn/m4ij03z2.png)

Is this the expected behaviour?

For now, I wrote a hack to get around this:

```ruby
def track_once(experiment_name)
  experiment = Split::ExperimentCatalog.find(experiment_name)
  version = experiment ? experiment.version : 0
  key = "tracked_#{experiment_name}_v#{version}"
                                                              
  already_tracked = session.has_key?(key)
                                                              
  ab_finished(experiment_name, reset: false) unless already_tracked
                                                              
  session[key] ||= true
end
```

I'm on split `v1.4.4`, and I'm starting the `ab_test` with the following code:

```ruby
<% ab_test(:contact_request_cta_label, 'Show phones', 'Call') do |cta_text| %>
```

**Comment by andrew** [comment]
I don't think we ever want non-finished to go negative, that seems like we should merge your fix in to avoid that in future, fancy sending a pull request?

**Comment by herenow** [comment]
Yep, I'll get on this issue.

@andrew I just wan't to confirm that when we set `ab_finished(:test, reset: false)`, the ab test completion should be unique, so if the user has already finished the given test, we should not count him again. Is that it?

**Comment by andrew** [comment]
@herenow can you give the latest release a try, it contains this fix: https://github.com/splitrb/split/pull/408 which might solve the problem already

**Comment by herenow** [comment]
@andrew Everything is working fine now 👍

**Comment by andrew** [comment]
Sweet!
