### ISSUE TITLE
Extraneous requests to RedisAdapter

### ISSUE THREAD

**Issue by karmakaze** [splitrb/split#406]
When running in an environment with many api/app servers every request round-trip makes a difference. I believe that there are places in the code where unnecessary requests are made.
One example is at https://github.com/splitrb/split/blob/master/lib/split/trial.rb#L70-L71
Each `@user[@experiment.key]` will make a network request in RedisAdapter.

**Comment by andrew** [comment]
Any others that you've spotted @karmakaze?

**Comment by karmakaze** [comment]
I scanned through looking for other `user[]` and didn't notice any. Closing.
