### ISSUE TITLE
Invalid uri error on was server

### ISSUE THREAD

**Issue by super-engineer** [splitrb/split#413]
I've been getting 
`ActionView::Template::Error (invalid uri scheme 'http'):` while calling the ab_testing method on an AWS server. Local Redis server is connecting without any errors. The problem happens when I'm trying to connect to an AWS redis server.

My config looks like this. Have changed few values from the url for privacy purpose.
`Split.configure do |config|`
`config.db_failover = true # handle redis errors gracefully`
`config.db_failover_on_db_error = -> (error) { Rails.logger.error(error.message) }`
`config.allow_multiple_experiments = true`
`config.enabled = true`
`config.persistence = Split::Persistence::RedisAdapter.with_config(lookup_by: -> (context) { context.current_user_identifier })`
`config.start_manually = true ## new test will have to be started manually from the admin panel. default false`
`config.include_rails_helper = true`
`config.redis_url = 'xyz-redis-staging.ykshs.12353.ldkse1.cache.amazonaws.com'`
`end`

The nginx error log shows the following error trace.

> App 29637 stderr:     /var/www/simpl-web-frontend/releases/20160610103131/vendor/bundle/ruby/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:416:in `_parse_options'
> App 29637 stderr:   /var/www/simpl-web-frontend/releases/20160610103131/vendor/bundle/ruby/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:81:in`initialize'
> App 29637 stderr:   /var/www/simpl-web-frontend/releases/20160610103131/vendor/bundle/ruby/2.2.0/gems/redis-3.3.0/lib/redis.rb:51:in `new'
> App 29637 stderr:   /var/www/simpl-web-frontend/releases/20160610103131/vendor/bundle/ruby/2.2.0/gems/redis-3.3.0/lib/redis.rb:51:in`initialize'
> App 29637 stderr:   /var/www/simpl-web-frontend/releases/20160610103131/vendor/bundle/ruby/2.2.0/gems/split-1.4.4/lib/split.rb:42:in `new'
> App 29637 stderr:   /var/www/simpl-web-frontend/releases/20160610103131/vendor/bundle/ruby/2.2.0/gems/split-1.4.4/lib/split.rb:42:in`redis='
> App 29637 stderr:   /var/www/simpl-web-frontend/releases/20160610103131/vendor/bundle/ruby/2.2.0/gems/split-1.4.4/lib/split.rb:59:in `redis'
> App 29637 stderr:   /var/www/simpl-web-frontend/releases/20160610103131/vendor/bundle/ruby/2.2.0/gems/split-1.4.4/lib/split/experiment_catalog.rb:7:in`all'
> App 29637 stderr:   /var/www/simpl-web-frontend/releases/20160610103131/vendor/bundle/ruby/2.2.0/gems/split-1.4.4/lib/split/experiment_catalog.rb:12:in `all_active_first'
> App 29637 stderr:   /var/www/simpl-web-frontend/releases/20160610103131/vendor/bundle/ruby/2.2.0/gems/split-1.4.4/lib/split/dashboard.rb:20:in`block in class:Dashboard'

**Comment by andrew** [comment]
This issue is over a year old, I'm going to close it now but feel free to comment and request it be reopened if you still need it.
