### ISSUE TITLE
Set-Cookie value and expires mashed together with sinatra 1.4.5 and sinatra-contrib 1.4.2

### ISSUE THREAD

**Issue by karmakaze** [splitrb/split#423]
The response contains a header like the following:
`Set-Cookie: split=%7B%3Avalue%3D%3E%22%7B%5C%22wbff_test%5C%22%3A%5C%22alter_a%5C%22%7D%22%2C+%3Aexpires%3D%3E2016-07-10+14%3A22%3A58+-0400%7D; domain=localhost; path=/; HttpOnly`

when expecting something of the form:
`Set-Cookie: split=%7B%22wbff_test%22%3A%22alter_a%22%7D; expires=Sun, 10 Jul 2016 18:22:58 -0000; domain=localhost; path=/; HttpOnly`

**Comment by karmakaze** [comment]
Here's a workaround that I'm using in config/initializer/split.rb
```ruby
module Persistence
    class CookieAdapter
      def initialize_with_workaround(context)
        @context = context
        initialize_without_workaround(context)
      end
      alias_method_chain :initialize, :workaround

      private
      def set_cookie_with_workaround(value)
        response = @context.try(:response)
        if response
          response.set_cookie(:split, :value => JSON.generate(value), :expires => @expires)
        else
          set_cookie_without_workaround(value)
        end
      end
      alias_method_chain :set_cookie, :workaround
    end
end
```

**Comment by andrew** [comment]
This issue is over a year old, I'm going to close it now but feel free to comment and request it be reopened if you still need it.
