### ISSUE TITLE
Overriding variation across page loads

### ISSUE THREAD

**Issue by ccallebs** [splitrb/split#427]
There doesn't seem to be a way to override variations across page loads. It'd be helpful to have a dashboard button next to the variation to do this.

I can take point on this if it's a welcome feature.

**Comment by andrew** [comment]
@ccallebs that sounds good, PR to review would be sweet

**Comment by ccallebs** [comment]
@andrew Opened a PR, sorry it took me a month. Better late than never. :)

**Comment by ccallebs** [comment]
@andrew I'm closing this since the feature is in master now.
