### ISSUE TITLE
Getting ab_test decision with allow_multiple_experiments = 'control'

### ISSUE THREAD

**Issue by joedelia** [splitrb/split#429]
Hello there,

I'm testing out this library locally, and would like to run multiple tests at once by using `allow_multiple_experiments = 'control'`. However if I do that, I am unable to retrieve the decision in the future: `ab_test()` will always return `control` even for the same test.

Example (with `allow_multiple_experiments = 'control'`):

```  
# First page load
ab_test(:test1, 'control', 'alternate')  # control
ab_test(:test2, 'control', 'alternate') # alternate

# Second page load
ab_test(:test1, 'control', 'alternate')  # control
ab_test(:test2, 'control', 'alternate') # control
```

Am I doing something wrong?

Thank you!

Joe

**Comment by Vasfed** [comment]
Looks like with `allow_multiple_experiments = 'control'` there's some bug causing this, but `allow_multiple_experiments = true` works fine. Currently debugging this exact issue

**Comment by Vasfed** [comment]
Got this behavior too, sent #432 PR

**Comment by joedelia** [comment]
Thanks for that! I tried looking into it but had no idea how the project was organized :) Looking forward to PR being merged.

Joe
