### ISSUE TITLE
Reauthorize on coveralls

### ISSUE THREAD

**Issue by Vasfed** [splitrb/split#431]
Cannot browse coverage (for example - [here](https://coveralls.io/builds/7611524/source?filename=lib%2Fsplit%2Fuser.rb) )
> SOURCE NOT AVAILABLE
> The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

**Comment by andrew** [comment]
@Vasfed done!
