### ISSUE TITLE
Q: Read current test version

### ISSUE THREAD

**Issue by nnikolic** [splitrb/split#438]
Hello Split team,

First I would like to say big thanks for providing this great lib. It makes AB testing super easy, helps us a lot with iterations and finding the best solutions on our platform. Super cool.

Now I have a question. I could not find any helper which can give us the current version of an ongoing test (on session level). I am pointing to something similar to Devise's current_user helper. Something like current_ab_version(:test_name). Do you have something like that implemented. If not, do you plan to include it soon?
Also it would be helpful to have a helper which can check if test has started already or not - something like ab_test_started?(:test_name).

Thanks in advance.

**Comment by andrehjr** [comment]
Hi there, 

Right now, it's possible to use the `ab_user.active_experiments` helper to get a list of on going experiments(and values).

I'm closing a few older issues.. sorry for that. Thanks for opening this report!
