### ISSUE TITLE
Multiple FrontEnd Servers - is it possible to aggregate results to one Dashboard?

### ISSUE THREAD

**Issue by adamfrank86** [splitrb/split#449]
My App has a few FrontEnd servers.
As far as I know, the Split Dashboard shows stats per one server only, which already is a problem, since it shows only part or the load balanced.
Besides, this is problematic, since one server can start the test, and the other can finish it. This will result with many incorrect stats and confusion. 

Is it possible to aggregate all the results in the Split Dashboard?

**Comment by kholbekj** [comment]
I assume the answer is just to use the same redis server across the board?

**Comment by adamfrank86** [comment]
Yes, I tried this, but it had a bug, which was fixed in the latest release.
Thanks for the help anyway!
