### ISSUE TITLE
Document how to set up Split for an RSpec request spec

### ISSUE THREAD

**Issue by andrewhavens** [splitrb/split#452]
I'm trying to figure out how to configure/set up Split to be able to use correctly in my request spec. In a previous controller spec, I had something like this:

``` ruby
controller.ab_test 'some-test', 'no', 'yes'
```

However, now in my request spec, I don't have access to the controller, so I'm not sure how to set up this data. How can this be accomplished? And please also document this in the readme to help others who may also run into this question.

**Comment by ccallebs** [comment]
@andrewhavens Not sure if you've already figured this out, but I've historically done this the following way:

``` ruby
allow_any_instance_of(ApplicationController).to receive(:ab_test).with('some-test').and_return('yes')
```

It's better practice to wrap the split code in a separate class though, so you wouldn't have to stub ApplicationController directory.

**Comment by petrbela** [comment]
Vanity has a `chosen` method to set the response manually. https://github.com/assaf/vanity#testing
Haven't seen such feature in split but seems like it shouldn't be too difficult to add (essentially an algorithm that always returns the given thing).

**Comment by eliotsykes** [comment]
Create this in `spec/support/split_helper.rb` and ensure its `require`-d by `rails_helper.rb` or `spec_helper.rb`:
 
```rb
module SplitHelper
  def use_ab_test(alternatives_by_experiment)
    allow_any_instance_of(Split::Helper).to receive(:ab_test) do |_receiver, experiment|
      alternative = alternatives_by_experiment.fetch(experiment)
    end
  end
end

RSpec.configure do |config|
  config.include SplitHelper
end
```

In your spec, you can force an experiment to use an alternative of your choice:

```rb
it "registers using experimental signup" do

  use_ab_test some_experiment_name: "some_alternative_name"

  post "/signups", ...

  ...
end
```

Source: https://github.com/eliotsykes/rails-testing-toolbox/blob/master/split_helper.rb

**Comment by andrew** [comment]
@eliotsykes would you be up for contributing this tip to a section on testing in the readme?

**Comment by eliotsykes** [comment]
Absolutely, would be a pleasure to @andrew 👍 ! I'll get round to it in the next few days.
