### ISSUE TITLE
Multiple experiments only filters on named "control" instead of actual control

### ISSUE THREAD

**Issue by sgup** [splitrb/split#461]
I see that this allows you to run multiple experiments at once:

`config.allow_multiple_experiments = 'control'`

However, why does the name of the option have to be "control"? I see an option showing up with _control_ next to it. The problem is I already have a test underway where none of the options were specifically named "control", but the proper control option is marked.

**Comment by serodriguez68** [comment]
I have the same question here.  

Does the option has to be literally named control (i.e `ab_test :cta_copy, 'control', 'my_other_option' do |option|`) or will it work just by writing the 'current status' first?

**Comment by andrehjr** [comment]
Currently, the alternative must be called control for allow_multiple_experiments = 'control' to work as stated on the README. It's kinda confusing because on the dashboard and other parts of split the first alternative is called 'control'.

(Cleaning up some old issues)
