### ISSUE TITLE
Be able to get current test group without providing options

### ISSUE THREAD

**Issue by henrik** [splitrb/split#468]
I thought I could do this:

``` ruby
# Start test
ab_test("my_test", "group A", "group B")

# Later, check their group
which_group = ab_test("my_test")
```

But it seems all arguments (including the group names) need to be provided each time. It would be nice if that was not required, if you know that the test has already been started.

**Comment by andrew** [comment]
I have a feeling that you can do this if you use the yaml config approach in the readme

**Comment by henrik** [comment]
Ah, yes, it looks that way. Thank you. Would be nice to have this with the inline version as well, but I see how that could be a little complicated to implement. I'll close this ticket.
