### ISSUE TITLE
2.2.0 upgrade backwards incompatible (loses data)

### ISSUE THREAD

**Issue by henrik** [splitrb/split#469]
It looks like our running tests were reset when we upgraded from 2.1.0 to 2.2.0, though the changelog or version numbers did not suggest backwards incompatibility.

A hypothesis is that removing Redis namespace as a dependency also changed the Redis keys so Split stopped using old keys and made new ones instead. Have not investigated this a lot, but glancing at Redis keys, this seems like it could be the case.

If you think this is correct, maybe the README could include a backwards-compatibility warning for this version?

**Comment by andrew** [comment]
Yeah 2.2.0 should really be 3.0.0, I fucked up there, do you fancy sending a pr to add a note to the readme?

**Comment by henrik** [comment]
No worries :) Done!
