### ISSUE TITLE
Can't load dashboard with Rails 5

### ISSUE THREAD

**Issue by alexvbush** [splitrb/split#473]
Hi, I can't make the dashboard work in my Rails 5 app. This is what I get:

![screenshot 2017-02-03 14 04 15](https://cloud.githubusercontent.com/assets/311077/22610329/d010e3c2-ea19-11e6-8dd5-c0d9aaec17ba.png)

**Comment by bugtender** [comment]
It has been fixed by #470. But not in release version.
Maybe you can reinstall Split with the master branch.

**Comment by alexvbush** [comment]
@bugtender will give it a shot this week!

**Comment by alexvbush** [comment]
@bugtender it worked!!! Nice!

**Comment by alexvbush** [comment]
when is the next version with this patch will be released? I don't feel comfortable pointing to master branch in my project.

**Comment by andrew** [comment]
@alexvbush I'll try to get a release out this weekend

**Comment by mtyeh411** [comment]
@andrew i noticed this is not a part of the latest release.  do we have an ETA for that?

**Comment by andrew** [comment]
@mtyeh411 also blocked on https://github.com/splitrb/split/issues/476

**Comment by alexvbush** [comment]
Experiencing this issue in prod now actually

**Comment by alexvbush** [comment]
@andrew do you need a hand with #476 !

**Comment by alexvbush** [comment]
?

**Comment by andrew** [comment]
@alexvbush yes please, currently very busy working on @librariesio and don't have much free time for split

**Comment by andrew** [comment]
@alexvbush just released v3.0.0: https://github.com/splitrb/split/releases/tag/v3.0.0

**Comment by alexvbush** [comment]
@andrew thank you!
