### ISSUE TITLE
Broken tests on travis, blocking new releases

### ISSUE THREAD

**Issue by andrew** [splitrb/split#476]
The test suite is broken on travis at the moment, not sure what's going on there but I don't have any free time to investigate at the moment but I don't feel comfortable pushing any new releases until it's fixed.

Any help replicating or fixing appreciated

**Comment by mtyeh411** [comment]
is this now resolved? 
https://github.com/splitrb/split/pull/479

**Comment by andrew** [comment]
@mtyeh411 yep, just released 3.0.0: https://github.com/splitrb/split/releases/tag/v3.0.0

**Comment by mtyeh411** [comment]
thanks!
