### ISSUE TITLE
"undefined method cookies" when using Force for User in Dashboard

### ISSUE THREAD

**Issue by joffotron** [splitrb/split#480]
Ruby 2.3.3 / Rails 5.0.1

initializers/split.rb:
```ruby
Split.configure do |config|
  config.enabled = true
  config.persistence = :cookie
  config.include_rails_helper = true
  config.redis = ENV['REDIS_URL'] || "redis://redis:6379"
end
```

Clicking on "Force for current user" results in:

```
2017-03-27 01:27:26 - NoMethodError - undefined method `cookies' for #<Split::Dashboard:0x007f5f1015a9e8>:
 	/bundle/gems/split-2.2.0/lib/split/persistence/cookie_adapter.rb:9:in `initialize'
 	/bundle/gems/split-2.2.0/lib/split/user.rb:8:in `new'
 	/bundle/gems/split-2.2.0/lib/split/user.rb:8:in `initialize'
 	/bundle/gems/split-2.2.0/lib/split/dashboard.rb:34:in `new'
 	/bundle/gems/split-2.2.0/lib/split/dashboard.rb:34:in `block in <class:Dashboard>'
 	/bundle/gems/sinatra-2.0.0.beta2/lib/sinatra/base.rb:1643:in `call'
```

If I configure persistence using the SessionAdapter, it works as I would expect.

Is this a Bug? A Misconfiguration?

**Comment by andrew** [comment]
Looks like a bug to me

**Comment by jgoulah** [comment]
we're also seeing this

**Comment by andrehjr** [comment]
Hey @andrew, to fix this on Sinatra/Rails I think we need to change the implementation of the CookieAdapter to use Rack directly(same way Sinatra::Cookies does), that way it should work for both Rails/Sinatra or any Rack app.

I made a simple test, and that works. Want me to take a stab on this and submit a PR?

**Comment by andrew** [comment]
That'd be great thanks!
