### ISSUE TITLE
how to access experiments in mailers, bg jobs

### ISSUE THREAD

**Issue by petrsigut** [splitrb/split#489]
We are trying to access user experiment variant from mailer (or anywhere current_user or helpers are not available) and I do not know how to achieve it.

We are storing data for logged users in Redis, so it should be somehow available.

Is there way to pass @user to the ab_test? Or somehow set this context?

Write helper method to and manually dig it from Redis seems wrong:)

**Comment by petrsigut** [comment]
We came up with this simple solution, looking forward to any comments or ideas.

```
class SplitStore 
   def initialize
     redis = Redis.new
     @namespace = Redis::Namespace.new(:persistence, :redis => redis)
   end
 
   def find_for_user(experiment, user_id)
     @namespace.hget user_id, experiment.to_s
   end
end
```

**Comment by andrew** [comment]
@petrsigut seems like a fairly elegant solution give that there's no access to the session in mailers/bg jobs 👍

**Comment by eazynow** [comment]
Hey - I'm hitting a similar issue. I'm just trying to understand how it integrates with split itself. 

That class @petrsigut suggested, just seems to get a hash lookup from redis to lookup the current values. What if the user didn't have experiment data already at this point? Isn't that where split would work out and generate the initial values and populate redis?

Or (and this is entirely possible as I've only been looking at split for an hour or so) Am I missing something more fundamental here?

**Comment by dwesty17** [comment]
I'm running into this as well @andrew. Would be nice to add some docs for this. I'm still not sure I understand the solution @petrsigut posted

**Comment by petrsigut** [comment]
(if relevant, we switched to https://github.com/ankane/field_test)

**Comment by dwesty17** [comment]
Thanks @petrsigut! I'll check that out
