### ISSUE TITLE
Experiments disappeared?

### ISSUE THREAD

**Issue by rtlechow** [splitrb/split#492]
I was running an experiment for a few days, and the `experiments` set disappeared from redis, which left the web dashboard empty. Not really sure if this is expected behaviour or a bug. Any idea why this would happen?

**Comment by andrew** [comment]
Not off the top of my head, how's the memory usage on your redis? Perhaps it filled up and evicted the older keys?

**Comment by rtlechow** [comment]
Was using a very churny db, my bad.
