### ISSUE TITLE
How can I pass a user as context to ab_finished?

### ISSUE THREAD

**Issue by ericgross** [splitrb/split#497]
I have a user in an experiment that my admin is viewing in an admin interface. How can I call `ab_finished` for the user being looked at rather than the admin user?

**Comment by andrew** [comment]
@ericgross I don't think this is possible at the moment, but I'd be happy to accept a pull request to add that functionality

**Comment by hstove** [comment]
I have a similar use case - wouldn't it be possible by overriding the `context`? For example:

~~~ruby
class SplitContext
  attr_reader :current_user
~~~

**Comment by hstove** [comment]
I have a similar use case - wouldn't it be possible by overriding the `context`?

~~~ruby
class SplitContext
  attr_reader :current_user
  def initialize(user)
    @current_user = user
  end
~~~

Then:

~~~ruby
experiment = Split::ExperimentCatalog.find_or_create('color', 'red', 'blue')
# `my_user` is the user you want to 'complete' the experiment
split_user = Split::User.new(SplitContext.new(my_user)
alternative = split_user[experiment.key]
trial = Split::Trial.new(:experiment => experiment, alternative: alternative)
trial.complete!
~~~

Am I right that this code should work?

**Comment by andrew** [comment]
Looks like that should work

**Comment by ericgross** [comment]
Yes, this works for me!
