### ISSUE TITLE
Please update wiki about redis-configuration

### ISSUE THREAD

**Issue by yyamanoi1222** [splitrb/split#507]
Hello

I want to use redis different host.
I read this [section](https://github.com/splitrb/split/wiki/Tutorial#redis-configuration)  and create  
config/initializers/split.rb and config/split.yml  
but this error has occured
```
.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/redis-3.3.3/lib/redis/client.rb:416:in `_parse_options': invalid uri scheme 'localhost' (ArgumentError)
```

So Please update wiki

config/initializers/split.rb
```
rails_root = ENV['RAILS_ROOT'] || File.dirname(__FILE__) + '/../..'
rails_env = ENV['RAILS_ENV'] || 'development'

split_config = YAML.load_file(rails_root + '/config/split.yml')
Split.redis = 'redis://' + split_config[rails_env]

```

**Comment by andrehjr** [comment]
You are correct @yyamanoi1222, the tutorial had invalid instructions for the Redis Configuration. Fixed now!
