### ISSUE TITLE
Dashboard pagination

### ISSUE THREAD

**Issue by GeorgeGorbanev** [splitrb/split#517]
In my application number of experiments grows up to 100. So when I trying to request split dashboard it responds about 30 seconds.

I want to propose to add experiments pagination on dashboard. I can create pull request soon. What you think about It?

**Comment by andrew** [comment]
Sounds like a great idea 👍

**Comment by GeorgeGorbanev** [comment]
Solution: https://github.com/splitrb/split/pull/518
