### ISSUE TITLE
Weighted alternatives not working

### ISSUE THREAD

**Issue by neyp** [splitrb/split#521]
I'm using v.3.20 and weighted alternatives don't seem to be working. 

I start an abtest with:
```
alternatives = {"alt1" => 9}, "alt2"
ab_test(:example, alternatives)
```

When I fetch the experiment with `Split::ExperimentCatalog.find('example')`, the `@weight` attribute of both Split::Alternative are equal to 1.

**Comment by brianeroth** [comment]
Also seeing this issue. Any thoughts?

**Comment by PatrickMcGrath29** [comment]
@brianeroth finally made the PR haha, https://github.com/splitrb/split/pull/548
