### ISSUE TITLE
Manual bucket logic

### ISSUE THREAD

**Issue by alexhalliday** [splitrb/split#537]
We use Split extensively but there is a use case we have which is causing some issues. How would we manually bucket a user based on the last 2 digits of their user id? 

Is there a way with split to setup your own bucketing rule, but use the rest of the gem as-is? 

Any help would be greatly appreciated.

**Comment by andrew** [comment]
You could write your own Algorithm class, there are three existing ones: https://github.com/splitrb/split/tree/master/lib/split/algorithms

The documentation on adding your own is a little sparse: https://github.com/splitrb/split/blob/master/README.md#algorithms

Example pull request for adding one (you don't need to actually send it as a PR in your case): https://github.com/splitrb/split/pull/475/files
