### ISSUE TITLE
undefined method `ab_test' for #<#<Class:0x007fcc0cfb19b0>:0x007fcc0e5f8de0> 

### ISSUE THREAD

**Issue by markburns** [splitrb/split#54]
If I call ab_test in a view I get the exception mentioned.

Including Split::Helper in my ApplicationHelper will solve this, but not sure of the cause. 

I'm presuming it's something to do with load order of Split and the `if defined? Rails` not getting executed, but can't seem to get to the bottom of it, so no failing test case at the moment.

Have you encountered this before?

**Comment by dmitry** [comment]
Adding in initializer should help:

```
Split.configure do |config|
  config.include_rails_helper = true
end
```

**Comment by zinkkrysty** [comment]
I have the same issue. Though it is strange it started occurring after using the `ab_test` method with 4 arguments (name, version_1_hash, version_2_hash, version_3_hash). If I change it back to 3 and then to 4 then it works but only until the next server restart.

`config.include_rails_helper = true` didn't work for me

`include Split::Helper` in `application_helper.rb` worked.
