### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by andrew** [splitrb/split#543]
At the end of January I'll be stepping down as maintainer of the split project, I've not used it in a long time and I've got my hands full with [other projects](https://octobox.io) at the moment.

If you're interested in becoming a maintainer of this and the 7 other repositories in [the organization](https://github.com/splitrb) then please leave a message here.

If no maintainer is found by 1st Feb 2019 then I'll be archiving the repositories on GitHub (i.e. making them read-only), the gems will remain published on [rubygems.org](https://rubygems.org/gems/split) but no future updates will be released.

Thanks to everyone who's used and contributed to split over the past 8 years!

**Comment by andrehjr** [comment]
Hi @andrew, I can give it a try :) I wouldn't like to see this project die

Also, the company I work for also uses split in production

**Comment by andrew** [comment]
Awesome, I’ll drop you an email tomorrow!
