### ISSUE TITLE
Get test bucket only if user has been previously bucketed

### ISSUE THREAD

**Issue by nick41496** [splitrb/split#547]
We have a use case where we would like an equivalent call to `ab_test` but one which only returns a bucket if a user has been previously bucketed by a call to `ab_test`. So this method would return the bucket for a user who has already been bucketed, but would return control if the user had not been previously bucketed. In the past, we have queried our persistence store directly, but that strategy doesn't return the winning bucket for finished tests (at least for our persistence method).

Does something like this already exist? If not, would you accept it in a PR? I'm happy to build it.

**Comment by andrehjr** [comment]
Hi @nick41496 

Can you give more details on the use case?

I'm open to PRs, though I'd like to better understand the use case first. 

Right now, we do have a few possibilities of extending the ab_test behavior via custom algorithms. And also, combined experiments. Which should work for most scenarios.

Thanks!  ✨

**Comment by nick41496** [comment]
We would use this when we want one AB test to determine behavior in 2 different locations, but we only want users to be bucketed if they hit the "first" location.

For example, we send an email which will trigger another email and we want to AB test these emails. We only want users who get the initial email to be bucketed in the test, which will then determine the look of both emails. So we would call `ab_test` from the first email, and then in the second email we need a way to get the bucket, but only for users who have already been bucketed by the first email. Other users should see the control.

Does that make more sense?

**Comment by andrehjr** [comment]
Thanks! Yes, it makes more sense now.

I think you should be able to do that with [Combined Experiments](https://github.com/splitrb/split#combined-experiments). Have you tried it?

**Comment by nick41496** [comment]
I haven't yet but I'll look into that now.

Thank you very much! 🙂
