### ISSUE TITLE
Undefined local variable ro method `request'

### ISSUE THREAD

**Issue by nwallace** [splitrb/split#549]
Just tried to upgrade from 3.2.0 to 3.3.1, and [this commit](https://github.com/splitrb/split/commit/98ce5539bdd4b2e82ac30145817051386c0e628c) broke our setup. [This commentor](https://github.com/splitrb/split/commit/98ce5539bdd4b2e82ac30145817051386c0e628c#commitcomment-30058029) seems to have had a similar issue, but I don't think he filed a bug.

We use Split outside the context of web requests pretty regularly, for example to compare the effectiveness of two email templates, where the emails are generated by background jobs. Using the Redis store makes this possible.

I guess this isn't exactly intended usage, but it's very useful. We do many split tests in process with the web request, but we do some out-of-process too.

Here's a minimal example project that shows how it used to work, but now breaks: https://github.com/nwallace/split-request-issue

Basically, we used to be able to use an object like this:

```
class ContextWrapper
  include Split::EncapsulatedHelper
end
```

Then we could use it like this to run experiments:

```
ContextWrapper.new.ab_test("my_experiment") # => an experiment alternative
```

But now that code fails, with "undefined local variable or method `request' for #<Split::EncapsulatedHelper::ContextShim:...>"

Gem backtrace:

```
/home/nathan/.gem/ruby/2.6.1/gems/split-3.3.0/lib/split/helper.rb:125:in `exclude_visitor?'
/home/nathan/.gem/ruby/2.6.1/gems/split-3.3.0/lib/split/helper.rb:15:in `ab_test'
/home/nathan/.gem/ruby/2.6.1/gems/split-3.3.0/lib/split/encapsulated_helper.rb:32:in `ab_test'
```

I hoped that I would be able to fix the issue by defining a dummy `request` method on my wrapper class, but that didn't work. Would it be possible to be protect against undefined `request` consistently? Looks like some places in `Split::Helper` check `defined?(request)`, but `#exclude_visitor?` doesn't

**Comment by andrehjr** [comment]
Hi @nwallace!

For now, seems like the easiest solution is to check for `defined?(request)` on `#exclude_visitor?`. Can you test against 27cf04c ? It does seem to be working with your example.

Right now, split mostly works by including the Split::Helper which assumes a lot of things, like if a request is present. However, I do plan on adding better support for 'non-view' ab_test calls such as yours! But I'll need to change a few things first to do that.

Thanks very much for getting the example project and your investigation!

**Comment by nwallace** [comment]
@andrehjr Yes, looks like that solves our issue! Thank you :heart: We'll keep an eye out for more official support for these kinds of things
