### ISSUE TITLE
Production: No experiments have started yet, you need to define them in your code and introduce them to your users.

### ISSUE THREAD

**Issue by feliperaul** [splitrb/split#550]
I'm on version 3.3.1. 

We have a simple ab_test being called on every single page view:

`<% ab_test :statistical_analysis, 'true', 'false' %>`

On development, we can access the web dashboard and see the counters increasing. If we reset them, a single page refresh is enough to see the experiment again.

But in production we are seeing "No experiments have started yet, you need to define them in your code and introduce them to your users." in the dashboard.

Our split config is pretty simple:

```
Split.configure do |config|
  config.db_failover = true # handle redis errors gracefully
  config.db_failover_on_db_error = proc{|error| Rails.logger.error(error.message) }
  config.allow_multiple_experiments = true
end
```

So we don't specify anything special about our redis connection. We use Redis for sidekiq just fine.

Using `redis-cli monitor` I can see that on every page reload there are a bunch of redis commends being executed due to Split gem; but the dashboard remains empty.

Any clues on how I can debug this?

**Comment by feliperaul** [comment]
Well, I checked the source code as much as I could, but could never figure out what was going on. Just changing the name of the experiment and it worked...

**Comment by MyklClason** [comment]
@feliperaul Through my own testing, it looks like your experiment may need at least 1 participant before it appears.

**Comment by feliperaul** [comment]
@myklclason we had thousands! It was set in all of our pages. The second we changed the experiment name it started appearing with no other changes. Unfortunately we couldn’t dig further at the time.

**Comment by MyklClason** [comment]
Huh, odd. No clue then. Interesting.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
