### ISSUE TITLE
Pricing Test: Conversion Rate + Revenue

### ISSUE THREAD

**Issue by themire** [splitrb/split#562]
Is it possible to do the following using Split:

With..

Variant A: Product Price: £10
Variant B: Product Price: £20

...I will get the conversion rates of each variant out of the box which is great.

However, is there anyway I could get the sum of the revenue for each variant?

If I could get access to the user's variant when I do `ab_finished` I could save the data somewhere myself which would do.

Thanks!

**Comment by andrehjr** [comment]
I don't think there's a way to get that sum out of the box right now :/

But there is a callback for when an experiment finishes. And you should be able to get that info from there.  See: `on_trial_complete` https://github.com/splitrb/split#trial-event-hooks

**Comment by andrehjr** [comment]
I'll go ahead and close this issue as `on_trial_complete` should be enough for you at this moment.
