### ISSUE TITLE
Split Dashboard Error: Parameters must be strictly positive

### ISSUE THREAD

**Issue by reneklacan** [splitrb/split#563]
![image](https://user-images.githubusercontent.com/1935686/56379014-0508b900-620f-11e9-8d7d-efb5a9cb75f2.png)

Any idea what might be causing this?

I will try to debug it and post any additional info.

**Comment by reneklacan** [comment]
This seems to be an issue:

```
PRODUCTION [33] pry(main)> alternative.completed_count
=> 10
PRODUCTION [34] pry(main)> alternative.participant_count
=> 8
```

We somehow got into a state where we have more completions than participants which shouldn't be possible.

**Comment by MyklClason** [comment]
I ran into this issue as well. Unclear how to get into a valid state. Though *may* be related to using the "force for current user", as I saw at one point participant count was negative when I was using this.

**Comment by reneklacan** [comment]
To resolve it, I just manually modified the stored value in Redis like this:

```
PRODUCTION [2] pry(main)> experiments = Split::ExperimentCatalog.all_active_first

PRODUCTION [6] pry(main)> experiments[2].calc_winning_alternatives
ArgumentError: Parameters must be strictly positive
from .../vendor/bundle/ruby/2.6.0/gems/simple-random-1.0.3/lib/simple-random/simple_random.rb:103:in `beta'

PRODUCTION [11] pry(main)> experiments[2].calc_beta_params
=> {#<Split::Alternative:0x00005638469c71e0
  @experiment_name="new_conversation_started",
  @name="new_desktop",
  @weight=1>=>[11, -1],
 #<Split::Alternative:0x00005638469c71b8
  @experiment_name="new_conversation_started",
  @name="old_desktop",
  @weight=1>=>[3, 5],
 #<Split::Alternative:0x00005638469c7190
  @experiment_name="new_conversation_started",
  @name="new_mobile",
  @weight=1>=>[5, 1],
 #<Split::Alternative:0x00005638469c7168
  @experiment_name="new_conversation_started",
  @name="old_mobile",
  @weight=1>=>[7, 3]}

PRODUCTION [27] pry(main)> alternative = experiments[2].alternatives[0]

PRODUCTION [33] pry(main)> alternative.completed_count
=> 10

PRODUCTION [34] pry(main)> alternative.participant_count
=> 8

PRODUCTION [41] pry(main)> key = alternative.send :key

PRODUCTION [43] pry(main)> Split.redis.hset key, 'completed_count', 0
```

**Comment by andrehjr** [comment]
Hi there,

Yes, this seems related to the use of 'force for current user' as it persists the alternative for the current user directly, which bypasses some stuff. i.e: not incrementing the participant_count when needed

Causing this error, because when an experiment finishes it always increments the completed_count.

**Comment by ShylahChiera** [comment]
Was experiencing the same issue. Meddled around in Redis data similar to @reneklacan 's answer and found that both my variations (A and B) had higher `completed_count` than `participant_count` set them all back to 0 and now up and running again.
