### ISSUE TITLE
Older experiments disappeared after updating split version

### ISSUE THREAD

**Issue by sleepydada** [splitrb/split#564]
I updated my split gem from 2.1.0 to 3.3.2, and older experiments disappeared in the dashboard . I had to change my Redis url fom `#{Settings.get(:redis, :host)}:6379` to `redis://#{Settings.get(:redis, :host)}:6379` because I got a wrong url error after updating the gem. Could that be why they disappeared? Is there any way I can prevent or fix it?

**Comment by andrehjr** [comment]
Hi @sleepydada,

On 2.2.0 (which should've been 3.0.0) there was a change that removed redis-namespace as a dependency, which in turn changed the name of a few keys (removing the 'split' prefix from the key). 

The data from your old experiments are still on your Redis instance, you need to either 'rename' them removing the `split` prefix or bring back the prefix on Redis.

You could do something like this, as someone mentioned by someone on #425 comments that had the same problem, and it should fix it:

```
redis = Redis::Namespace.new(url: 'redis://localhost:6379', namespace: 'split')
Split.redis = redis
```

There was a note added on the changelog stating that 2.2.0 was not fully backwards compatible.. but I understand that you did not expect that data itself to vanish :(

**Comment by sleepydada** [comment]
Thank you! I'll try that report back :)
