### ISSUE TITLE
Testing homepage, but if user goes to any page on site it gets tracked as participant 

### ISSUE THREAD

**Issue by masudhossain** [splitrb/split#569]
So we're testing two homepages using partials, so we put the tracker inside a view. 

But problem is, if a user goes to ANY page on our site..they get put under participant. Even though they never saw the homepage in the first place. 

How can we track participants that ONLY saw either of the homepages ?

**Comment by andrehjr** [comment]
Hi @masudhossain ! 

By tracker, you mean the `ab_test` helper? When that gets called the user in question is put under participant for the given experiment. If it's not being called on the 'current page' it should not set the user as a participant for your experiment.

Can you share some code as an example?

**Comment by masudhossain** [comment]
@andrehjr I just did some testing, and it seems spit gem only does this "bug" on a page that has the sites iframe loaded in. I'm not iframe loading in the homepage however, it's a different page. 

Code is in views/homes/index
`<% ab_test(:homepage_test, "homes/partials/old_homepage", "homes/partials/new_homepage") do |alternative| %>`
    `<%= render alternative %>`
`<% end %>`

**Comment by andrehjr** [comment]
Oh, nice! Glad you've found the issue.  My first guess was that it was something related to the iframes somehow.

I'll go ahead and close this issue then!
