### ISSUE TITLE
Experiment `on_winner_choose` hook

### ISSUE THREAD

**Issue by GenaMinenkov** [splitrb/split#571]
Hey folks.

In our application, we have to know when a particular experiment's winner was chosen.

There are already implemented integration point such as:
- `on_trial`
- `on_trial_choose`
- `on_trial_complete`
- `on_before_experiment_reset`
- `on_experiment_reset`
- `on_experiment_delete`

I propose to implement a hook like:
- `on_winner_choose`

If you have a solution which doesn't require the implementation of this hook please let me know.

If a solution doesn't exist, please let me know if you are interested in this functionality or not. It looks like I will add it anyway, but in prospect, it can be part of the library.

**Comment by andrehjr** [comment]
Closed by #574 !
