### ISSUE TITLE
Bug when ab_finished action takes place before the ab_test action

### ISSUE THREAD

**Issue by gnanou** [splitrb/split#576]
When an experiment e.g. `:my_experiment` already exists in Redis and then for a user we have the following flow:
1. `ab_finished(:my_experiment, reset: false)`
2. `ab_test(:my_experiment)`
3. `ab_finished(:my_experiment, reset: false)`

then the `completed` counter is not increased as expected the second time `ab_finished` is called.

This happens because the first time `ab_finished` is called with `reset: false` option, it will change the `ab_user` state, setting the experiment's `finished_key` to `true` [here](https://github.com/splitrb/split/blob/84beb9e3e08b42020f2b96c22bf7615cb79320d6/lib/split/helper.rb#L60). This way, when `ab_finished` is called again, it will return before the `completed` counter is increased due to this [check](https://github.com/splitrb/split/blob/84beb9e3e08b42020f2b96c22bf7615cb79320d6/lib/split/helper.rb#L49).

I have a simple solution ready for this issue, checking if the experiment about to finish is active for the user. If you agree I can make a PR.

**Comment by andrehjr** [comment]
That makes sense to me. Feel free to send a PR.

If the user is not active on that experiment, calling ab_finished should not change the ab_user state. 

Your other PR is also on my TODO list for review. Thanks for your recent contributions!

**Comment by gnanou** [comment]
Great, I will send the PR, thanks a lot!
