### ISSUE TITLE
Split::ExperimentCatalog.all returns incomplete experiment data

### ISSUE THREAD

**Issue by aleksclark** [splitrb/split#589]
**Describe the bug**
When split tests are configured to use 'complex' behavior, calls to `Split::ExperimentCatalog.all` result in only partial experiment configuration being returned, in contrast to `Split::ExperimentCatalog.find_or_create`

Additionally, I consider it to be surprising behavior that `Split::ExperimentCatalog.all` doesn't return configured-but-not-persisted experiments

**To Reproduce**
1. Configure a split test using weighted alternatives
2. Persist split test using `Split::ExperimentCatalog.find_or_create(my_experiment)`
3. Call `Split::ExperimentCatalog.all`
4. See returned experiments have weights of 1
5. Call `Split::ExperimentCatalog.find_or_create(my_experiment)`
6. Observe returned experiment has correct weights

**Expected behavior**
I would expect that `Split::ExperimentCatalog.all` return the proper configuration for each experiment, and that it return all configured experiments, not just the ones that have been persisted.

**Additional context**
```
irb(main):007:0> Split::ExperimentCatalog.all
=> [#<Split::Experiment:0x0000557fa810fb08 @name="invisible_split_test", @alternatives=[#<Split::Alternative:0x0000557fa82da0f0 @experiment_name="invisible_split_test", @name="control", @weight=1>, #<Split::Alternative:0x0000557fa82da078 @experiment_name="invisible_split_test", @name="red", @weight=1>, #<Split::Alternative:0x0000557fa82da050 @experiment_name="invisible_split_test", @name="blue", @weight=1>], @goals=[], @resettable=false, @algorithm=Split::Algorithms::WeightedSample, @metadata={"search_sub_suffix"=>"invisible-test", "similar_sub_suffix"=>"invisible-test", "lanes"=>[0, 1], "locales"=>["en", "es"], "ticket"=>"ES-1337"}, @alternative_probabilities={}>]
irb(main):008:0> Split::ExperimentCatalog.find_or_create(:invisible_split_test)
=> #<Split::Experiment:0x0000557fa82f6660 @name="invisible_split_test", @alternatives=[#<Split::Alternative:0x0000557fa82fd028 @experiment_name="invisible_split_test", @name="control", @weight=0.5>, #<Split::Alternative:0x0000557fa82fcfb0 @experiment_name="invisible_split_test", @name="red", @weight=0.25>, #<Split::Alternative:0x0000557fa82fcf38 @experiment_name="invisible_split_test", @name="blue", @weight=0.25>], @goals=[], @resettable=nil, @algorithm=Split::Algorithms::WeightedSample, @metadata={"search_sub_suffix"=>"invisible-test", "similar_sub_suffix"=>"invisible-test", "lanes"=>[0, 1], "locales"=>["en", "es"], "ticket"=>"ES-1337"}, @alternative_probabilities={}>
irb(main):009:0> 

```

**Comment by andrehjr** [comment]
Hi @aleksclark,  this issue was fixed by #570. I'll release 3.3.3 with that fix soon.
