### ISSUE TITLE
Consider excluding "Pinterest" from bots list

### ISSUE THREAD

**Issue by huoxito** [splitrb/split#605]
Hi all!

We depend heavily on split.rb for our application experiments and we recently realized that pinterest users were not being bucketed properly.

We believe that's due to "Pinterest" matching all of these user agents https://developers.whatismybrowser.com/useragents/explore/software_name/pinterest-app/ instead of only ignoring a bot itself. Wonder if anyone else has experienced similar issues? Would you consider removing that key from the bots list?

thanks a lot for this project ❤️

**Comment by andrehjr** [comment]
Hi! Indeed, it seems we're not only blocking the Pinterest bot but everything that matches Pinterest. 

This needs to be addressed, we should only be blocking the [Pinterest Bot](https://help.pinterest.com/en/business/article/pinterest-crawler).

For now, a "quick fix" for you would be to add this to your initializer. 

```ruby
Split.configure do |config|
  config.bots.delete['Pinterest']
end 
```
