### ISSUE TITLE
How to create a helper for Minitest instead of RSpec?

### ISSUE THREAD

**Issue by osmarluz** [splitrb/split#638]
Hi everyone!
This is more of a question than a bug, actually. But I'll try to give as many details as possible.
The question is: how to create a helper for `ab_test` method to be used on testing with `Minitest` instead of `RSpec`?
I've tried a couple of solutions but none of them worked, so I'm out of ideas.

My first try was just converting the `RSpec` helper to use `Minitest Mocha` syntax:

```ruby
# Create a file with these contents at 'spec/support/split_helper.rb'
# and ensure it is `require`d in your rails_helper.rb or spec_helper.rb
module SplitHelper

  # Force a specific experiment alternative to always be returned:
  #   use_ab_test(signup_form: "single_page")
  #
  # Force alternatives for multiple experiments:
  #   use_ab_test(signup_form: "single_page", pricing: "show_enterprise_prices")
  #
  def use_ab_test(alternatives_by_experiment)
    Split::Helper.any_instance.stubs(:ab_test) do |_receiver, experiment|
      alternatives_by_experiment.fetch(experiment) { |key| raise "Unknown experiment '#{key}'" }
    end
  end
end
```

The problem here is that `Split::Helper` is a module, therefore it doesn't respond to `any_instance`.

After trying the solution above I added a breakpoint to the view that contains the `ab_test` method call (using `pry`) to see how this method was getting called and this was the result:

```ruby
$ find-method ab_test

Split::Helper
Split::Helper#ab_test
```

So the `ab_test` is an **instance method** on module `Split::Helper`, which I don't know how to stub using Minitest. I tried stubbing the class that includes `Split::Helper` by doing `Split::EncapsulatedHelper::ContextShim.any_instance.stubs(:ab_test).returns 'a'` but no success either.

Any suggestions on how to solve this?

**Comment by andrehjr** [comment]
Hi @osmarluz 

If you're using ActionDispatch::IntegrationTest for example, is kinda hard to stub Split::Helper. 

Instead of stubbing ab_test, I think you can stub Split::User directly to return the experiment you want. 

```ruby
Split::User.any_instance.stubs(:[]).returns('a')
```

Let me know if this works.

**Comment by andrehjr** [comment]
For the future, split should provide a better API to do this. Instead of relying on stubs from other libs.. I have some ideas :)

I'll go ahead and close this for now.

**Comment by osmarluz** [comment]
@andrehjr thanks for the help, @andrehjr! It worked well for the test I needed to write :smile:
