### ISSUE TITLE
Rspec failing in ab_test method

### ISSUE THREAD

**Issue by gauravgupwk** [splitrb/split#646]
Hello Team,
I am using **gem 'split', "~> 3.4.1", :require => 'split/dashboard'**
Using below ruby and rails version
`ruby 2.7.2`
`rails 6.0.3.4`
`gem rspec 3.9.0`

it's working fine for all the apis but when I am calling this method `ab_test('my_first_experiment')` with rspec and I got the below exception  
  **ab_test("my_first_experiment")**
  ** ArgumentError Exception: unknown stub request 127.0.0.1**
This my code snippet 
```
    post do
        test_name = params[:test_name].to_sym
        if params[:action_type] == "ab_test"
          ab_test("my_first_experiment") do |alternative, meta|
            return {alternative: alternative, meta: meta}
          end
        elsif params[:action_type] == "ab_finished"
          ab_finished(test_name)
        else
          raise_404("A/B test not found")
        end
      rescue StandardError
        raise_api_error("Something went wrong. Are you sure the experiment exists?")
      end
```
Could you please guys help me and let me know if I missed something.

**Comment by andrehjr** [comment]
Hey @gauravgupwk can you post some more code? Maybe you're stubbing all network calls? `** ArgumentError Exception: unknown stub request 127.0.0.1**` the full stack trace would help.

Although, the following works just fine to me. Maybe it's something related to your spec setup.
```ruby 
class AccountsController < ApplicationController
  def index
    render plain: ab_test('my_exp', 'foo', 'bar')
  end
end

# spec
require 'rails_helper'

RSpec.describe AccountsController, type: :controller do
  it 'render an option from split' do
    get :index
    expect(response.body).to be_in(['foo', 'bar'])
  end
end
```
