### ISSUE TITLE
Multiple tests with the same prefix (e.g. menu and menu_underline) will result in the second test being recalculated at every request

### ISSUE THREAD

**Issue by dorianmariefr** [splitrb/split#667]
**Describe the bug**

I have multiple experiments, including `menu` and `menu_underline`. My `menu` experiment works fine but my `menu_underline` experiment changes on every requests randomly and I get as many users as I have requests instead of having the same number of users based on their cookie

**To Reproduce**

```rb
Split.configure do |config|
  config.persistence = :cookie
  config.persistence_cookie_length = 30.days
  config.allow_multiple_experiments = true
end
```

```rb
    @ab_test_menu = ab_test(:menu, "bottom-fixed-text", "top-images")
    @ab_test_menu_underline =
      ab_test(:menu_underline, "no-underline", "underline")
```

- Refresh the page many times
- See wrong numbers in split dashboard

**Expected behavior**

One user should consistently see the same experiment on every page refresh

**Additional context**

All my finished are in the same place:

```rb
      ab_finished(:menu, reset: false)
      ab_finished(:menu_underline, reset: false)
      ab_finished(:header, reset: false)
      ab_finished(:participate, reset: false)
      ab_finished(:or, reset: false)
      ab_finished(:register_or_login, reset: false)
```

Renaming to `underline` instead of `menu_underline` fixed the issue for now

**Comment by andrehjr** [comment]
This was actually fixed by #661 (which I totally forgot about it 😅)

I can release another version to include that. Can you try it out with main branch?

**Comment by dorianmariefr** [comment]
tried the main branch, looks fixed to me, thanks

<img width="837" alt="Screenshot 2021-11-11 at 08 31 31" src="https://user-images.githubusercontent.com/58794487/141256743-3734d8a0-cd6a-43fd-b54b-c2a9e8806bc6.png">

**Comment by dorianmariefr** [comment]
maybe time to release the 4.0.0? I will be using the 4.0.0.pre2 meanwhile

**Comment by andrehjr** [comment]
Probably, yes @dorianmariefr ! Will do that in the following days.

Thanks for trying it 4.0.0.pre2 :)
