### ISSUE TITLE
 When split cookie is a valid, json encoded String, a NoMethodError is raised

### ISSUE THREAD

**Issue by knarewski** [splitrb/split#695]
**Describe the bug**
When `split` cookie is a valid, json encoded String, a `NoMethodError` is raised.

**To Reproduce**
1. Save the following script as `test.rb`
```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'split'
  gem 'sinatra'
  gem 'sinatra-contrib'
  gem 'redis', '~> 4.8'
end

Split.configure do |config|
  config.persistence = :cookie
  config.experiments = { foo: { alternatives: ['a', 'b'] } }
end

class MySinatraApp < Sinatra::Base
  helpers Sinatra::Cookies
  helpers Split::Helper

  get '/' do
    ab_test(:foo)
  end
end

MySinatraApp.run!
```
2. Run: `ruby test.rb`
3. On a separate terminal window, invoke `curl -H "User-Agent: not-a-bot" -H 'Cookie: split="valid-json-string"' localhost:4567`
4. See the app crashing with ``NoMethodError - undefined method `keys' for "valid-json-string":String``

**Expected behavior**
The invalid content is ignored, similarly to how unparseable JSON is ignored

**Additional context**
The trivial check in [cookie_adapter.rb](https://github.com/splitrb/split/blob/29c6c073f858433ded223fd17f25572eaf8dd81e/lib/split/persistence/cookie_adapter.rb#L73) works for me:
```ruby
              parsed = JSON.parse(cookies)
              parsed.is_a?(String) ? {} : parsed
```

I'm happy to submit a PR if desired

**Comment by andrehjr** [comment]
Hi @knarewski! Thanks for the issue and the repro!

Please send a PR 🎉 We should also protect it against other types. if JSON.parse returns anything other than a Hash, split wouldn't know how to handle it.

An integer would also break:
```
curl -H "User-Agent: not-a-bot" -H 'Cookie: split=1' localhost:4567
```

If I remember correctly, this issue should happens with json >= 2.0. Because the behavior of JSON.parse changed.

**Comment by knarewski** [comment]
Hi @andrehjr ! Thank you for such a swift response 🚀 ! I prepared a fix, but it's blocked by an unrelated CI failure. I'm happy to submit a PR once the CI fix is merged: https://github.com/splitrb/split/pull/696
