### ISSUE TITLE
CROSSSLOT keys issue when using redis cluster

### ISSUE THREAD

**Issue by naveen-chidhambaram** [splitrb/split#709]
The change introduced as part of [this PR](https://github.com/splitrb/split/pull/632) does not work with the Redis Cluster setup. The `redis.rename` method call raises an error with the message `CROSSSLOT Keys in request don't hash to the same slot`.

**Solution:**
- In Cluster mode, both the keys of [RENAME](https://redis.io/commands/rename/) command must be in the same hash slot.
- Use [Hash tags](https://redis.io/docs/reference/cluster-spec/#hash-tags) to allot the same slot for the keys.

```
def persist_list(list_name, list_values)
  if list_values.length > 0
    redis.multi do |multi|
      tmp_list = "#{list_name}_tmp"
      tmp_list_tag = redis_namespace_used? ? "#{Split.redis.namespace}:#{list_name}" : list_name
      tmp_list << "{#{tmp_list_tag}}"
      multi.rpush(tmp_list, list_values)
      multi.rename(tmp_list, list_name)
    end
  end

  list_values
end

private

def redis_namespace_used?
  Redis.const_defined?("Namespace") && Split.redis.is_a?(Redis::Namespace)
end
```

Can we port the above changes into the gem?

**Comment by andrehjr** [comment]
Hi, thanks for issue! Yes, please do open a PR 🙏

I'm thinking if there's a way we could avoid referencing Redis::Namespace directly. Or if we could rewrite this method without using rename. That way, we wouldn't need to worry about Hash tags. I'll do some further investigation. it's been a while since I did the original PR.

**Comment by naveen-chidhambaram** [comment]
We considered the below approach of using `del` and `rpush` instead of using `rename`. Below are the reasons for not proceeding with this approach.
- In redis, when a command fails, all the other commands in the queue are processed and will not stop the processing of commands ([reference](https://redis.io/docs/interact/transactions/#:~:text=It%27s%20important%20to%20note%20that%20even%20when%20a%20command%20fails%2C%20all%20the%20other%20commands%20in%20the%20queue%20are%20processed%20%E2%80%93%20Redis%20will%20not%20stop%20the%20processing%20of%20commands)).
- Redis does not support rollbacks of transactions as well. That is when a command fails within a redis transaction, the subsequent commands are not executed and redis doesn’t rollback the previously executed commands within that transaction ([reference](https://redis.io/docs/interact/transactions/#:~:text=queued%20at%20all.-,What%20about%20rollbacks%3F,-Redis%20does%20not)).

```
def persist_list(list_name, list_values)
  if list_values.length > 0
    redis.multi do |multi|
      multi.del(list_name)
      multi.rpush(list_name, list_values)
    end
  end

  list_values
end
```

**Comment by naveen-chidhambaram** [comment]
@andrehjr Can you please review the comment and PR https://github.com/splitrb/split/pull/710

**Comment by andrehjr** [comment]
I'll look into this some time this week. I had some personal issues that kept me away 😓

**Comment by andrehjr** [comment]
Closed by https://github.com/splitrb/split/pull/710
